usethis::use_package( "thinkr" )
golem::add_module( name = "selections" )
golem::add_module( name = "name_of_module2" )
golem::add_fct( "helpers" ) 
golem::add_utils( "helpers" )
golem::add_js_file( "script" )
golem::add_js_handler( "handlers" )
golem::add_css_file( "custom" )
usethis::use_data_raw( name = "my_dataset", open = FALSE ) 
usethis::use_test( "app" )
usethis::use_vignette("grimenet")
devtools::build_vignettes()
usethis::use_github()
usethis::use_travis()
usethis::use_appveyor()
rstudioapi::navigateToFile("dev/03_deploy.R")
